all:
  children:
    containers:
      hosts:
        ansible:
    pve:
      hosts:
        hermes:
        netuno:
        poseidon:
    ssh:
      hosts:
        brucutu:
        brucutuIV:
        brucutuV:
        brucutuVI:
        sites:
      vars:
        open_to: authusers
    web:
      hosts:
        cache:
          ansible_port: 2227
        caos:
          ansible_port: 2225
        cosmo:
          ansible_port: 2226
      children:
        svapin:
          hosts:
            bibdigital:
            www:
              ansible_port: 2224
          vars:
            open_to: webadm
    windows:
      hosts:
        192.168.57.169:
