all:
  children:
    cloud:
      hosts:
        bidu:
        cocomidas:
        iris:
          ansible_port: 2224
        metis:
          ansible_port: 2224
        moiras:
          ansible_port: 2223
        moros:
          ansible_port: 2222
        mot:
          ansible_port: 2225
        mysql:
          ansible_port: 2225
        shiny:
          ansible_port: 2223
        tefnut:
        yue:
          ansible_port: 2223
    container:
      hosts:
        ansible:
        ate:
        athena:
        clotho:
        contas:
        fradim:
        kerberos:
        midas:
        sambabaca:
        unifi:
        www301:
    lab:
      hosts:
        ete:
    pve:
      hosts:
        hermes:
        netuno:
        poseidon:
    ssh:
      hosts:
        brucutu:
        brucutuIV:
        brucutuV:
        brucutuVI:
        hades1:
        hades2:
        sites:
      vars:
        open_to: authusers
    staff:
      hosts:
        compras4a3d-l:
        svtes9b85-l:
    web:
      hosts:
        cache:
          ansible_port: 2227
        caos:
          ansible_port: 2225
        cosmo:
          ansible_port: 2226
      children:
        svapin:
          hosts:
            bibdigital:
            www:
              ansible_port: 2224
          vars:
            open_to: webadm
    windows:
      hosts:
        192.168.57.169:
