all:
  children:
    cloud:
      hosts:
        backupcloud:
          ansible_port: 2225
        #bidu:
        #dnscloud:
        #  ansible_port: 2226
        #iris:
        #  ansible_port: 2224
        #moiras:
        #  ansible_port: 2223
        #mysql:
        #  ansible_port: 2225
        sambadc:
      children:
        nfs:
          hosts:
            moros:
              ansible_port: 2222
            mot:
              ansible_port: 2222
    container:
      hosts:
        #ansible:
        #athena:
        caneco:
        #clotho:
        #dnscache:
        #fradim:
        #labcead:
        #lollo:
        #meshcentral:
        #ocs:
        #sambabaca:
        #saori:
        #switchfw:
        #unifi:
        #www301:
        xicrinho:
        zoneminder:
    lab:
      hosts:
        ete:
        gaspar:
        melchior:
      children:
        labets:
          hosts:
            serge:
            kid:
            lynx:
            guile:
            norris:
            nikki:
            viper:
            riddel:
            karsh:
            korcha:
            luccia:
            poshul:
            zappa:
            orcha:
            radius:
            glenn:
            leena:
            miki:
        labmae:
          hosts:
            #aldebaran: dualboot
            #horologium: dualboot
            #hydra: dualboot
            #indus: dualboot
            lacerta:
            lepus:
            libra:
            monoceros:
            norma:
            ophiucus:
            puppis:
            reticulum:
            sextans:
            sirius:
    dualboot:
      hosts:
    pve:
      hosts:
        #hermes:
        #netuno:
        #poseidon:
    ssh:
      hosts:
        hades:
        hades2:
        site:
      children:
        brucutuX:
          hosts:
            brucutu:
            brucutuIV:
            brucutuVI:
    staff:
      hosts:
        compras4a3d-l:
        svtes9b85-l:
        caema60a-wl:
        portaria-a:
        N045018848:
    web:
      hosts:
        #cache:
        #  ansible_port: 2227
        #caos:
        #  ansible_port: 2225
        #cosmo:
        #  ansible_port: 2226
      children:
        svapin:
          hosts:
            #bibdigital:
            #  ansible_port: 2228
            #www:
            #  ansible_port: 2224
          vars:
            open_to: webadm
    windows:
      hosts:
        caem06c3-w:
        caem8cb0-wl:
        caemb358-wl:
        caemf13b-wl:
        cea01-w:
        cea02-w:
        cea03-w:
        cea04-w:
        cea05-w:
        cea06-w:
        cea07-w:
        cea08-w:
        cea09-w:
        cea10-w:
        cea11-w:
        cea12-w:
        cea13-w:
        cea14-w:
        cea15-w:
        secmae1607-w:
        secmae4be3-w:
        secmaefe04-w:
        secmap4bde-w:
        secmat13e8-w:
        secmat4abe-w:
        caema60a-wl:
        caema60c-wl:
        N045014621:
      children:
        win_classroom:
          hosts:
            velikanova-w:
