all:
  children:
    cloud:
      hosts:
        bidu:
        cocomidas:
        iris:
          ansible_port: 2224
        metis:
          ansible_port: 2224
        moiras:
          ansible_port: 2223
        moros:
          ansible_port: 2222
        mot:
          ansible_port: 2225
        mysql:
          ansible_port: 2225
        shiny:
          ansible_port: 2223
        tefnut:
        yue:
          ansible_port: 2223
    container:
      hosts:
        ansible:
        ate:
        athena:
        clotho:
        contas:
        fradim:
        kerberos:
        lollo:
        midas:
        sambabaca:
        unifi:
        www301:
    lab:
      hosts:
        ete:
        gaspar:
        melchior:
        mario-bros:
        bucuorme:
    pve:
      hosts:
        hermes:
        netuno:
        poseidon:
    ssh:
      hosts:
        hades1:
        hades2:
        sites:
      vars:
        open_to: authusers
      children:
        brucutuX:
          hosts:
            brucutu:
            brucutuIV:
            brucutuV:
            brucutuVI:
    staff:
      hosts:
        compras4a3d-l:
        svtes9b85-l:
        caema60a-wl:
        portaria-a:
    web:
      hosts:
        cache:
          ansible_port: 2227
        caos:
          ansible_port: 2225
        cosmo:
          ansible_port: 2226
      children:
        svapin:
          hosts:
            bibdigital:
            www:
              ansible_port: 2224
          vars:
            open_to: webadm
    windows:
      hosts:
        192.168.57.169:
        caem06c3-w:
        caem8cb0-wl:
        caemb358-wl:
        caemf13b-wl:
        cea01-w:
        cea02-w:
        cea03-w:
        cea04-w:
        cea05-w:
        cea06-w:
        cea07-w:
        cea08-w:
        cea09-w:
        cea10-w:
        cea11-w:
        cea12-w:
        cea13-w:
        cea14-w:
        cea15-w:
        secmae1607-w:
        secmae4be3-w:
        secmaefe04-w:
        secmap4bde-w:
        secmat13e8-w:
        secmat4abe-w:
        caema60a-wl:
        caema60c-wl:
      children:
        win_classroom:
          hosts:
            velikanova-w:
