# no futuro esse playbook pode ser desmembrado
# grupos com playbook próprio: lab e staff

- name: cloud linux
  hosts: cloud
  roles:
    - role: base
    - role: ssh

- name: container linux
  hosts: container
  roles:
    - role: base
    - role: ssh

- name: pve host linux
  hosts: pve
  roles:
    - role: base
    - role: ssh

- name: nfs cloud linux
  hosts: nfs
  roles:
    - role: base
    - role: ssh
    - role: sssd-ad

- name: ssh server linux
  hosts: ssh
  roles:
    - role: base
    - role: ssh
    - role: sssd-ad
# open_to: authusers

- name: web linux
  hosts: web
  roles:
    - role: base
    - role: ssh

- name: docker linux
  hosts: docker
  roles:
    - role: base
    - role: ssh
    - role: docker

- name: storage server
  hosts: storage_server
  roles:
    - role: base
    - role: ssh

- name: samba share hosts
  hosts: sambashare
  roles:
    - role: base
    - role: ssh
    - role: sambashare
